import type { Metadata } from "next";
import { Roboto } from "next/font/google"
import "./globals.css";
import Header from "@/components/Header/Header";
import css from "./layout.module.css"
import ModalViewProvider from "@/components/ModalViewProvider/ModalViewProvider";
import BodyBackground from "@/hooks/BodyBackground";
import { AuthProvider } from "@/components/AuthProvider/AuthProvider";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-family",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
  return (
    <html lang="en">
			<body className={roboto.variable}>
				<div className={css.container}>
					<TanStackProvider>
						<AuthProvider>
							<ModalViewProvider>
								<Header />
								<BodyBackground />
								{children}
							</ModalViewProvider>
						</AuthProvider>
					</TanStackProvider>
				</div>

				<Toaster
          position="top-right"
          toastOptions={{
            duration: 6000,
            style: {
							fontSize: "18px"
            },
          }}
        />
			</body>
    </html>
  );
}
