import type { Metadata } from "next";
import { Roboto } from "next/font/google"
import "./globals.css";
import Header from "@/components/Header/Header";
import css from "./layout.module.css"
import ModalViewProvider from "@/components/ModalViewProvider/ModalViewProvider";
import BodyBackground from "@/hooks/BodyBackground";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-family",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
  return (
    <html lang="en">
			<body className={roboto.variable}>
				<div className={css.container}>
					<ModalViewProvider>
						<Header />
						<BodyBackground />
						{children}
					</ModalViewProvider>
				</div>
			</body>
    </html>
  );
}
